### ISSUE TITLE
搜车前端早读课 - 2016.01.21

### ISSUE THREAD

**Issue by xinyu198736** [souche/F2E-Morning-Reading#6]
《为 Java 说句公道话》看java工程师如何喷其他语言 http://gold.xitu.io/entry/569f17627db2a2005219973d

《gitflow备忘清单》清晰的可视化的表达gitflow的基本流程 http://danielkummer.github.io/git-flow-cheatsheet/index.zh_CN.html

《React.js pure render performance anti-pattern》https://medium.com/@esamatti/react-js-pure-render-performance-anti-pattern-fb88c101332f#.33rb3u7fk

《WHY REACT/REDUX IS AN INFERIOR PARADIGM》 http://staltz.com/why-react-redux-is-an-inferior-paradigm.html

《use WebRTC anywhere》https://github.com/contra/rtc-everywhere

**Comment by teamrun** [comment]
gitflow疑问: 

dev切出俩功能分支f/a和f/b, 由两个team开发, a先完成, 合并回dev, 切出release分支r/a, 然后b功能开发完, 合并会dev, 切出r/b, 如果此时发现a功能不能发布, b功能需要发布... 怎么搞~~ r/b已经在合并dev->切出r/b时带有了a的代码..

**Comment by xinyu198736** [comment]
@teamrun  是不是这样：
1. 合并回dev的都应该是达到发布状态的代码。
2. 限制发布，每周四发布，如果同一个repo上出现这种问题，则此次发布取消。

**Comment by teamrun** [comment]
feature完成就会合dev的: 

## 完成新特性
完成开发新特性。这个动作执行下面的操作.

* **合并 MYFEATURE 分支到 'develop'**
* 删除这个新特性分支
* 切换回 'develop' 分支
git flow feature finish MYFEATURE

## 发布新特性
你是否合作开发一项新特性？
发布新特性分支到远程服务器，所以，其它用户也可以使用这分支。

git flow feature publish MYFEATURE

**Comment by PeterRao** [comment]
@teamrun 我也有这样的疑问，a功能有bug只能在release上修复，如果修复不了，得延迟发布？
我觉得git flow的这套，适合很多人共同维护一个项目，有定期发布的时间点。
PS：亮亮好久不见啦
